# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de seguridad',
                'verbose_name_plural': 'Configuraciones de seguridad',
                'db_table': 'configuracion_seguridad',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('LOGIN_EXITOSO', 'Login exitoso'), ('LOGIN_FALLIDO', 'Login fallido'), ('LOGIN_BLOQUEADO', 'Login bloqueado'), ('LOGOUT', 'Logout'), ('CREAR', 'Creación de registro'), ('EDITAR', 'Edición de registro'), ('ELIMINAR', 'Eliminación de registro'), ('VER', 'Visualización de registro'), ('EXPORTAR', 'Exportación de datos'), ('ERROR', 'Error del sistema')], max_length=30, verbose_name='Tipo de evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('accion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('ERROR', 'Error')], default='EXITOSO', max_length=10, verbose_name='Estado')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'db_table': 'log_auditoria',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo_evento', 'fecha'], name='log_auditor_tipo_ev_042daf_idx'), models.Index(fields=['usuario', 'fecha'], name='log_auditor_usuario_6960f7_idx'), models.Index(fields=['ip_address', 'fecha'], name='log_auditor_ip_addr_f6bd36_idx')],
            },
        ),
    ]
