# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaRehabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del programa')),
                ('tipo', models.CharField(choices=[('educativo', 'Educativo'), ('laboral', 'Laboral'), ('psicologico', 'Psicológico'), ('deportivo', 'Deportivo'), ('artistico', 'Artístico')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_dias', models.PositiveIntegerField(default=30, verbose_name='Duración (días)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa de rehabilitación',
                'verbose_name_plural': 'Programas de rehabilitación',
                'db_table': 'programas_rehabilitacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rehabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('progreso', models.FloatField(default=0.0, verbose_name='Progreso (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin_prevista', models.DateField(blank=True, null=True, verbose_name='Fecha fin prevista')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha fin real')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitaciones', to='internos_app.interno', verbose_name='Interno')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='rehabilitacion_app.programarehabilitacion', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Rehabilitación',
                'verbose_name_plural': 'Rehabilitaciones',
                'db_table': 'rehabilitaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
