# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widgets_activos', models.JSONField(blank=True, default=list, verbose_name='Widgets activos')),
                ('tema', models.CharField(default='claro', max_length=20, verbose_name='Tema')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de dashboard',
                'verbose_name_plural': 'Configuraciones de dashboard',
                'db_table': 'configuracion_dashboard',
            },
        ),
    ]
