# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionRiesgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10, verbose_name='Nivel de riesgo')),
                ('score', models.FloatField(verbose_name='Puntuación (0-1)')),
                ('confianza', models.FloatField(default=0.0, verbose_name='Confianza (%)')),
                ('factores', models.JSONField(blank=True, default=dict, verbose_name='Factores determinantes')),
                ('modelo_version', models.CharField(default='v1.0', max_length=50, verbose_name='Versión del modelo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de predicción')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_ia', to='internos_app.interno', verbose_name='Interno')),
            ],
            options={
                'verbose_name': 'Predicción de riesgo IA',
                'verbose_name_plural': 'Predicciones de riesgo IA',
                'db_table': 'predicciones_riesgo',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
