# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10, null=True, verbose_name='Nivel de riesgo')),
                ('calificacion_riesgo', models.FloatField(blank=True, null=True, verbose_name='Calificación de riesgo (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('resultados', models.JSONField(blank=True, default=dict, verbose_name='Resultados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completada')),
                ('activo', models.BooleanField(default=True)),
                ('interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='internos_app.interno', verbose_name='Interno evaluado')),
                ('psicoplogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo responsable')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['completada'], name='evaluacione_complet_332615_idx'), models.Index(fields=['estado'], name='evaluacione_estado_777aa7_idx')],
            },
        ),
    ]
