# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo')),
                ('estado', models.CharField(choices=[('procesado', 'Procesado'), ('condenado', 'Condenado'), ('liberado', 'Liberado'), ('traslado', 'Trasladado')], default='procesado', max_length=20, verbose_name='Estado')),
                ('delito', models.CharField(blank=True, max_length=255, verbose_name='Delito imputado')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_liberacion_prevista', models.DateField(blank=True, null=True, verbose_name='Fecha de liberación prevista')),
                ('centro_penitenciario', models.CharField(blank=True, max_length=200, verbose_name='Centro penitenciario')),
                ('celda', models.CharField(blank=True, max_length=20, verbose_name='Celda')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interno',
                'verbose_name_plural': 'Internos',
                'db_table': 'internos',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['cedula'], name='internos_cedula_54ded5_idx'), models.Index(fields=['estado'], name='internos_estado_4f16ea_idx')],
            },
        ),
    ]
