# Generated by Django 4.2.13 on 2026-05-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('estadistico', 'Estadístico'), ('individual', 'Individual'), ('comparativo', 'Comparativo'), ('auditoria', 'Auditoría')], max_length=20, verbose_name='Tipo')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado / Ruta de archivo')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
