# Generated by Django 4.2.16 on 2026-05-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='formato',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=10, verbose_name='Formato interno'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Datos (JSON interno)'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('estadistico', 'Estadístico General'), ('individual', 'Individual (Internos)'), ('comparativo', 'Comparativo'), ('auditoria', 'Auditoría de Seguridad'), ('internos', 'Internos'), ('evaluaciones', 'Evaluaciones Psicológicas'), ('rehabilitacion', 'Rehabilitación'), ('ia_predictiva', 'IA Predictiva de Riesgo')], max_length=20, verbose_name='Tipo'),
        ),
    ]
